### ISSUE TITLE
Mongo image missing linux/amd64 platform 

### ISSUE THREAD

**Issue by AugustoEMoreira** [pulumi/tutorial-pulumi-fundamentals#11]
### What happened?

following the tutorial my pulumi file didn't work because the mongo container keep crashing, doing some drill down i found the problem being the mongo image is build for linux/amd64/v8 platform, which i believe is the platform for mac m1/m2.

### Expected Behavior

mongodb container to run

### Steps to reproduce

`docker run pulumi/tutorial-pulumi-fundamentals-database-local` in a linux platform

### Output of `pulumi about`

CLI          
Version      3.63.0
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.35.0
awsx    1.0.2
docker  3.6.1
nodejs  unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v18.16.0'

Current Stack: aumoreira/firstProject/dev

TYPE                                  URN
pulumi:pulumi:Stack                   urn:pulumi:dev::firstProject::pulumi:pulumi:Stack::firstProject-dev
pulumi:providers:docker               urn:pulumi:dev::firstProject::pulumi:providers:docker::default_3_6_1
docker:index/remoteImage:RemoteImage  urn:pulumi:dev::firstProject::docker:index/remoteImage:RemoteImage::frontendImage
docker:index/remoteImage:RemoteImage  urn:pulumi:dev::firstProject::docker:index/remoteImage:RemoteImage::backendImage
docker:index/network:Network          urn:pulumi:dev::firstProject::docker:index/network:Network::network
docker:index/remoteImage:RemoteImage  urn:pulumi:dev::firstProject::docker:index/remoteImage:RemoteImage::mongoImage
docker:index/container:Container      urn:pulumi:dev::firstProject::docker:index/container:Container::frontendContainer

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/aumoreira
User           aumoreira
Organizations  aumoreira, learnOrg

Dependencies:
NAME            VERSION
@pulumi/aws     5.35.0
@pulumi/awsx    1.0.2
@pulumi/pulumi  3.63.0
@types/node     16.18.23

Pulumi locates its logs in /tmp by default

### Additional context

i know i could build the image by myself, i'm just warning because it will break other users that use linux. 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by scottslowe** [comment]
@AugustoEMoreira Thanks for this report! You are correct---the Docker image referenced in the tutorial is indeed published only for `linux/arm64`, which would be the format used for any ARM-based systems (AWS Graviton, Apple Silicon, etc.). If you're running this from an Intel-based system, that's definitely a problem! We'll work on getting this fixed up ASAP.

**Comment by tlkamp** [comment]
Hello, this appears to still be an issue. I was able to resolve it by using the `pulumi/tutorial-pulumi-fundamentals-database` image (the one without the `-local` suffix).
