### ISSUE TITLE
Add more details into the root readme

### ISSUE THREAD

**Issue by aaronkao** [pulumi/tutorial-pulumi-fundamentals#4]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Can we add more details into the root readme? This is where a user lands when clicking "code repo" from the Learn pathway. Should have a bit more details to avoid confusion

**Comment by Kevjinx** [comment]
the '../README.md#Prerequistes' in /backend/src/readme.md leads to nothing
