### ISSUE TITLE
Fundamentals tutorial "container exited immediately"

### ISSUE THREAD

**Issue by jspablo** [pulumi/tutorial-pulumi-fundamentals#5]
### What happened?

Following the [Pulumi introduction tutorial](https://www.pulumi.com/learn/pulumi-fundamentals) I can't get the app running with the default MongoDB image.

### Steps to reproduce

After adding the containers step and executing `pulumi up` I get the following error:
```
docker:index:Container (mongo_container):
  error: 1 error occurred:
   * container exited immediately
```

By executing locally the container:

```
docker run -dit pulumi/tutorial-pulumi-fundamentals-database-local
```

I notice is not using the same image platform as the `backend` and `frontend` images:
```
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
```

### Expected Behavior

If building the image from this repo I can complete the tutorial but it would be great to update the docker hub image

### Actual Behavior

I can't complete the tutorial following the instructions

### Versions used

CLI          
Version      3.33.2
Go Version   go1.17.10
Go Compiler  gc

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

Backend        
Name           pulumi.com

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by nimbinatus** [comment]
Thanks for the report! You're correct regarding that it was built with a specific OS in mind; I've added it to my list of to-dos to make it more universal.

**Comment by ZeoX06** [comment]
Hi, as a workaround you can use the MongoDB image directly. 
Replace: pulumi/tutorial-pulumi-fundamentals-database-local --> mongo:4.4.13
